version: '3'

services:
  test-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
      - /home/afatt/Documents/Projects/docker-testing/csvfiles:/usr/src/app/test
    ports:
      - 80:80
